org.daxprotocol.core.config.default_encoding=UTF-8
org.daxprotocol.core.config.namespace.tag_prefix=CRM
org.daxprotocol.core.config.namespace.symbol=CUSTOMER
org.daxprotocol.core.config.namespace.description=Customer Relationship Management
