org.daxprotocol.core.config.default_encoding=UTF-8
org.daxprotocol.core.config.context.tag_prefix=CRM
org.daxprotocol.core.config.context.symbol=CUSTOMER
org.daxprotocol.core.config.context.description=Customer Relationship Management
